# Generated by Django 3.0.3 on 2020-03-05 19:50

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rfc', models.CharField(max_length=13, verbose_name='R.F.C')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=3)),
                ('indice_masa', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(choices=[('1', 'Pago mensual'), ('2', 'Pago diario')], max_length=1, verbose_name='Tipo de pago')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de pago')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=7)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios_uaz.Usuario', verbose_name='Usuario')),
            ],
        ),
    ]
